package edu.uark.registerapp.commands.transactions;

import edu.uark.registerapp.commands.ResultCommandInterface;
import edu.uark.registerapp.commands.exceptions.UnprocessableEntityException;
import edu.uark.registerapp.models.api.Product;
import edu.uark.registerapp.models.api.TransactionEntry;
import edu.uark.registerapp.models.entities.TransactionEntryEntity;
import edu.uark.registerapp.models.repositories.TransactionEntryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
public class AddProductToTransaction implements ResultCommandInterface<TransactionEntry> {
    @Override
    public TransactionEntry execute() {
        this.validateProperties();

        // Create a new ENTITY object from the API object details
        // We assume only quantity of 1 is initially added to Transaction.. Can be updated in cart
        final TransactionEntryEntity transactionEntryEntity =
                this.transactionEntryRepository.save(new TransactionEntryEntity(
                        this.transactionId,
                        this.apiProduct.getId(),
                        1,
                        this.apiProduct.getPrice()
                ));

        // Synchronize information generated by the database upon INSERT
        this.apiTransactionEntry = new TransactionEntry(transactionEntryEntity);

        return this.apiTransactionEntry;
    }

    // Helper Methods
    private void validateProperties() {
        if (this.transactionId.equals(null)) {
            throw new UnprocessableEntityException("transactionId");
        }

        if (this.apiProduct.equals(null)) {
            throw new UnprocessableEntityException("apiProduct");
        }
    }

    // Properties
    private UUID transactionId;
    public UUID getTransactionId() { return this.transactionId; }
    public AddProductToTransaction setTransactionId(final UUID transactionId) {
        this.transactionId = transactionId;
        return this;
    }

    private Product apiProduct;
    public Product getApiProduct() { return this.apiProduct; }
    public AddProductToTransaction setApiProduct(final Product apiProduct) {
        this.apiProduct = apiProduct;
        return this;
    }

    private TransactionEntry apiTransactionEntry;
    public TransactionEntry getApiTransactionEntry() { return this.apiTransactionEntry; }
    public AddProductToTransaction setApiTransactionEntry(final TransactionEntry apiTransaction) {
        this.apiTransactionEntry = apiTransaction;
        return this;
    }

    @Autowired
    private TransactionEntryRepository transactionEntryRepository;
}